name: project ci/cd flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests with Gradle Wrapper
        run: |
          cd backend
          ./gradlew test

      - name: Build Application with Gradle Wrapper
        run: |
          cd backend
          ./gradlew build
